### ISSUE TITLE
Agregar redes sociales

### ISSUE THREAD

**Issue by sebablasko** [niclabs/adkintunmobile#5]
Falta incorporar links o widgets a las redes sociales: twitter, facebook, etc.

**Comment by KarenDenisse** [comment]
La contraseña del Twitter quien la tiene? :) el link de Facebook es
https://m.facebook.com/adkintunmobile/

Les envío el comunicado de prensa, falta que lo apruebe Javier, pero si
creen que hace falta algo avísenme :)
